config/routes.rb
Cait::Application.routes.draw do

  root 'pages#home'

  resources :pages, :path => '' do
    collection do
      get 'home'
      get 'resume'
      get 'contact'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def resume
  end

  def contact
  end
end

app/views/layouts/_footer.erb
<div class="footer">
  <div class="left">
    Caitlin Ramsay
  </div>
  <div class="right">
    717-586-8389
  </div>
  <div class="clear"></div>
  <div class="love">
    Made with <%= link_to "Love", "http://tomprats.com/love"%>
  </div>
</div>

app/views/layouts/_head.erb
<head>
  <meta property="og:url" content="http://www.caitlinramsay.com">
  <meta property="og:title" content="CaitlinRamsay.com">
  <meta property="og:description" content="I have my own site, I'm cool now.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>CaitlinRamsay.com</title>
  <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Cabin" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag       "favicon.ico" %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_header.erb
<div class="navbar navbar-fixed-top">
  <ul class="nav nav-center">
    <li><%= link_to "Home", home_pages_path %></li>
    <li><%= link_to "Resume", resume_pages_path %></li>
    <li><%= link_to "Contact Me", contact_pages_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head" %>
  <body>
    <%= render "layouts/header" %>
    <div class="row-fluid">
      <div class="span6 offset3">
        <div class="<%= action_name %>">
          <%= yield %>
        </div>
        <%= render "layouts/footer" %>
      </div>
    </div>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="heading">
  <h3>
    Contact Caitlin
  </h3>
</div>
<div class="content">
  <div class="leftcolumn">
    <%= image_tag "caitlin.jpg", class: "contact-image" %>
  </div>
  <div class="rightcolumn">
    <p>
      This website is meant to build my skills and also my web presence.  If you have any questions or like my resume, let me know!
    </p>
    <p>
      <a href="mailto:caitielin1@comcast.net" target="_blank">caitielin1@comcast.net</a>
    </p>
  </div>
  <div class="clear"></div>
</div>

app/views/pages/home.html.erb
<div class="heading">
  <h3>Home</h3>
</div>
<div class="content">
  <h3>I'm so cute!</h3>
  <p>Like, why do I even have a website?  I am soooo much more adorbz in person!</p>
  <h3>Wait, is this even Caitlin?</h3>
  <p>Oops sorry, no it's not, not yet, but she'll learn how to do this soon!</p>
  <h3>How cute you say?</h3>
  <p>This cute!</p>
  <%= image_tag "caitlin_home.jpg", class: "center" %>
</div>

app/views/pages/resume.html.erb
<div class="heading">
  <h3>
    Resume
  </h3>
</div>
<div class="content">
  <div class="btn-group center">
    <%= link_to "Education", "#education", :class=> "btn btn-primary" %>
    <%= link_to "Work Related Experience", "#work-related-experience", :class=> "btn btn-primary" %>
    <%= link_to "Work Experience", "#work-experience", :class=> "btn btn-primary" %>
    <%= link_to "References", "#references", :class=> "btn btn-primary" %>
  </div>
  <br>
  <div class="row">
    <h3 id="education" class="anchor span11 offset1">Education</h3>
  </div>
  <div class="row">
    <div class="span10 pull-right">
      <div class="row">
        <div class="span12">
          <h4>Harrisburg Area Community College</h4>
          <div class="span10 pull-right">
            Children’s Developmental Psychology<br>
            Expected Graduation: May 2014
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <h3 id="work-related-experience" class="anchor span11 offset1">Work Related Experience</h3>
  </div>
  <div class="row">
    <div class="span10 pull-right">
      <div class="row">
        <div class="span12">
          <h4>Nanny</h4>
          <div class="span10 pull-right">
            2010-Present<br>
            Children ages newborn-4 years<br>
            Basic cooking<br>
            Experience with boys and girls<br>
            Experience with children who have developmental delays<br>
            Experience with sign language
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="span12">
          <h4>Dance Experience</h4>
          <div class="span10 pull-right">
            16 years of ballet<br>
            14 years of tap<br>
            13 years of hard shoe Irish<br>
            13 years of soft shoe Irish<br>
            11 years of jazz<br>
            7 years of pointe<br>
            6 years of hip hop<br>
            5 years of gymnastics<br>
            1 year of acrobatics
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="span12">
          <h4>Volunteer at the Lehman Caring Center</h4>
          <div class="span10 pull-right">
            Cared for children ages newborn-6<br>
            Played with children<br>
            Fed children<br>
            Put children to sleep<br>
            Helped with food preparation<br>
            Helped organize games and activities
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <h3 id="work-experience" class="anchor span11 offset1">Work Experience</h3>
  </div>
  <div class="row">
    <div class="span10 pull-right">
      <div class="row">
        <div class="span12">
          <h4>B*Dazzled Dance Studios</h4>
          <div class="span10 pull-right">
            January 2009- Present<br>
            Dance instructor for children ages 3-16<br>
            Taught Irish for 5 years<br>
            Taught ballet for 4 years<br>
            Taught tap for 4 years<br>
            Taught babies class for 4 years<br>
            Experience handling parental concerns<br>
            Experience making lesson plans<br>
            Experience with computers<br>
            Experience controlling children
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="span12">
          <h4>Tumble Town</h4>
          <div class="span10 pull-right">
            April 2013- Present<br>
            Watch and monitor children ages 2-12<br>
            Experience handling money<br>
            Customer service<br>
            Experience with misbehaving children
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <h3 id="references" class="anchor span11 offset1">References</h3>
  </div>
  <div class="row">
    <div class="span10 pull-right">
      <div class="row">
        <div class="span12">
          <div class="span10 pull-right">
            Feel free to <%= link_to "contact me", contact_pages_path %> for references.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>